apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-api
  namespace: pulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulse-api
  template:
    metadata:
      labels:
        app: pulse-api
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
      - name: pulse-api
        image: REPLACE_IMAGE
        ports:
        - containerPort: 8080
        env:
          - name: DB_USER
            value: root
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-root-password
                key: password
          - name: DB_HOST
            value: mysql.pulse.svc.cluster.local
          - name: DB_PORT
            value: "3306"
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: DJANGO_SECRET_KEY