apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-api
  namespace: pulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulse-api
  template:
    metadata:
      labels:
        app: pulse-api
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
      - name: pulse-api
        image: REPLACE_IMAGE
        ports:
        - containerPort: 8080
