apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse_api
  namespace: pulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulse_api
  template:
    metadata:
      labels:
        app: pulse_api
    spec:
      containers:
      - name: pulse_api
        image: REPLACE_IMAGE
        ports:
        - containerPort: 8080
