apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: pulse-api
  name: pulse-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pulse-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: pulse-api
    spec:
      containers:
        - args:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          env:
            - name: DEBUG
              value: "True"
          image: pulse-api
          name: pulse-api
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: pulse-api-cm0
      restartPolicy: Always

