# Generated by Django 5.2.5 on 2025-08-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="name", max_length=255)),
            ],
            options={
                "db_table": "tag",
            },
        ),
    ]
